version: "3"

services:
  db:
    image: mysql:5.7
    command:
      - --innodb_file_per_table
      - --innodb_file_format=Barracuda
      - --innodb_large_prefix
      - --character-set-server=utf8mb4
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
