version: "3.7"

services:
  db:
    image: postgres:10.7-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    restart: "no"
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: "no"
